require('dotenv').config()
const mongoose = require('mongoose')
const Recipe = require('../models/Recipe')

const recipes = [
  {
    title: 'Ayam Woku Belanga Asli Manado',
    description: 'Ayam Woku Belanga adalah masakan khas Manado yang kaya rempah, harum, dan penuh cita rasa. Kuahnya yang segar dengan kemangi dan daun jeruk membuat masakan ini sangat menggugah selera.',
    category: 'Indonesian',
    difficulty: 'Sedang',
    time: 45, price: 45000, servings: 4, rating: 4.8, reviews: 234,
    img: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '1 ekor', item: 'Ayam kampung, potong 12 bagian' },
      { amount: '3 batang', item: 'Serai, memarkan' },
      { amount: '5 lembar', item: 'Daun jeruk, buang tulang' },
      { amount: '2 ikat', item: 'Kemangi segar' },
      { amount: '3 buah', item: 'Tomat merah, potong dadu' },
      { amount: '2 sdm', item: 'Minyak goreng' },
      { amount: '400 ml', item: 'Air' },
      { amount: 'Secukupnya', item: 'Garam dan gula pasir' },
    ],
    spices: [
      { amount: '8 buah', item: 'Cabai merah keriting' },
      { amount: '5 buah', item: 'Cabai rawit merah' },
      { amount: '6 siung', item: 'Bawang merah' },
      { amount: '4 siung', item: 'Bawang putih' },
      { amount: '3 cm', item: 'Jahe' },
      { amount: '3 cm', item: 'Kunyit, bakar' },
    ],
    steps: [
      { step: 1, title: 'Siapkan bumbu halus', desc: 'Haluskan semua bahan bumbu menggunakan blender atau ulekan hingga benar-benar halus.' },
      { step: 2, title: 'Tumis bumbu', desc: 'Panaskan minyak dalam belanga. Tumis bumbu halus bersama serai hingga harum, sekitar 5-7 menit.' },
      { step: 3, title: 'Masukkan ayam', desc: 'Masukkan potongan ayam, aduk rata hingga terlumuri bumbu. Masak 5 menit hingga berubah warna.' },
      { step: 4, title: 'Tambahkan air', desc: 'Tuang air, masukkan daun jeruk dan tomat. Masak api sedang 20-25 menit hingga matang.' },
      { step: 5, title: 'Koreksi rasa', desc: 'Tambahkan garam dan gula secukupnya. Cicip dan sesuaikan.' },
      { step: 6, title: 'Masukkan kemangi', desc: 'Masukkan daun kemangi segar, aduk sebentar dan angkat dari api.' },
    ],
    tips: 'Gunakan ayam kampung untuk hasil lebih gurih. Membakar kunyit sebelum digunakan mengurangi bau langu.',
  },
  {
    title: 'Rendang Daging Sapi',
    description: 'Rendang daging sapi empuk dengan bumbu rempah khas Minang yang kaya cita rasa. Salah satu masakan terenak di dunia.',
    category: 'Indonesian',
    difficulty: 'Sulit',
    time: 120, price: 85000, servings: 6, rating: 4.9, reviews: 456,
    img: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '1 kg', item: 'Daging sapi, potong dadu' },
      { amount: '800 ml', item: 'Santan kental' },
      { amount: '4 lembar', item: 'Daun jeruk' },
      { amount: '2 batang', item: 'Serai, memarkan' },
      { amount: '3 lembar', item: 'Daun kunyit' },
      { amount: 'Secukupnya', item: 'Garam' },
    ],
    spices: [
      { amount: '10 buah', item: 'Cabai merah keriting' },
      { amount: '8 siung', item: 'Bawang merah' },
      { amount: '4 siung', item: 'Bawang putih' },
      { amount: '3 cm', item: 'Jahe' },
      { amount: '3 cm', item: 'Lengkuas' },
    ],
    steps: [
      { step: 1, title: 'Haluskan bumbu', desc: 'Blender semua bahan bumbu hingga halus.' },
      { step: 2, title: 'Masak santan', desc: 'Masak santan dengan bumbu halus dan rempah hingga mendidih.' },
      { step: 3, title: 'Masukkan daging', desc: 'Masukkan daging, masak api sedang sambil sesekali diaduk.' },
      { step: 4, title: 'Keringkan', desc: 'Kecilkan api, masak terus hingga santan mengering dan daging berwarna coklat gelap, sekitar 2 jam.' },
    ],
    tips: 'Sabar adalah kunci rendang. Semakin lama dimasak, semakin enak rasanya.',
  },
  {
    title: 'Nasi Goreng Spesial',
    description: 'Nasi goreng spesial dengan telur, sayuran, dan bumbu rahasia yang bikin ketagihan.',
    category: 'Indonesian',
    difficulty: 'Mudah',
    time: 25, price: 25000, servings: 2, rating: 4.7, reviews: 523,
    img: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '2 piring', item: 'Nasi putih kemarin' },
      { amount: '2 butir', item: 'Telur ayam' },
      { amount: '3 siung', item: 'Bawang putih, cincang' },
      { amount: '3 buah', item: 'Bawang merah, iris' },
      { amount: '2 sdm', item: 'Kecap manis' },
      { amount: '1 sdm', item: 'Saus tiram' },
      { amount: 'Secukupnya', item: 'Garam, lada, minyak goreng' },
    ],
    spices: [],
    steps: [
      { step: 1, title: 'Tumis bumbu', desc: 'Tumis bawang merah dan bawang putih hingga harum.' },
      { step: 2, title: 'Masukkan telur', desc: 'Masukkan telur, orak-arik hingga setengah matang.' },
      { step: 3, title: 'Masukkan nasi', desc: 'Masukkan nasi, aduk rata dengan bumbu.' },
      { step: 4, title: 'Bumbui', desc: 'Tambahkan kecap manis, saus tiram, garam, dan lada. Aduk rata di atas api besar.' },
      { step: 5, title: 'Sajikan', desc: 'Sajikan dengan acar, kerupuk, dan tomat segar.' },
    ],
    tips: 'Gunakan nasi sisa yang sudah dingin agar nasi goreng tidak lembek.',
  },
  {
    title: 'Spaghetti Bolognese Rumahan',
    description: 'Spaghetti Bolognese lezat dengan saus daging cincang kaya rempah untuk makan malam keluarga.',
    category: 'Western',
    difficulty: 'Mudah',
    time: 30, price: 35000, servings: 3, rating: 4.9, reviews: 189,
    img: 'https://images.unsplash.com/photo-1622973536968-3ead9e780960?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1622973536968-3ead9e780960?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '250 gr', item: 'Spaghetti' },
      { amount: '300 gr', item: 'Daging sapi cincang' },
      { amount: '1 buah', item: 'Bawang bombay, cincang' },
      { amount: '3 siung', item: 'Bawang putih, cincang' },
      { amount: '1 kaleng', item: 'Tomat crushed (400 gr)' },
      { amount: '2 sdm', item: 'Pasta tomat' },
      { amount: '1 sdt', item: 'Oregano kering' },
      { amount: 'Secukupnya', item: 'Garam, lada, keju parmesan' },
    ],
    spices: [],
    steps: [
      { step: 1, title: 'Rebus spaghetti', desc: 'Rebus spaghetti dalam air mendidih bergaram 8-10 menit hingga al dente. Tiriskan.' },
      { step: 2, title: 'Tumis aromatics', desc: 'Tumis bawang bombay hingga layu, masukkan bawang putih, tumis 1 menit.' },
      { step: 3, title: 'Masak daging', desc: 'Masukkan daging cincang, masak hingga kecoklatan.' },
      { step: 4, title: 'Tambahkan saus', desc: 'Masukkan pasta tomat, tomat crushed, dan oregano. Masak 15 menit api kecil.' },
      { step: 5, title: 'Sajikan', desc: 'Campurkan dengan spaghetti, taburi keju parmesan.' },
    ],
    tips: 'Tambahkan sedikit air rebusan pasta ke saus untuk membuat saus lebih creamy.',
  },
  {
    title: 'Burger Daging Homemade',
    description: 'Burger daging juicy dengan topping lengkap, lebih enak dan hemat dibuat sendiri di rumah.',
    category: 'Western',
    difficulty: 'Sedang',
    time: 40, price: 50000, servings: 2, rating: 4.6, reviews: 143,
    img: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '300 gr', item: 'Daging sapi cincang' },
      { amount: '2 buah', item: 'Roti burger' },
      { amount: '2 lembar', item: 'Keju slice' },
      { amount: '2 lembar', item: 'Selada' },
      { amount: '1 buah', item: 'Tomat, iris' },
      { amount: 'Secukupnya', item: 'Saus, mayones, mustard' },
      { amount: 'Secukupnya', item: 'Garam dan lada hitam' },
    ],
    spices: [],
    steps: [
      { step: 1, title: 'Buat patty', desc: 'Campur daging cincang dengan garam dan lada. Bentuk bulat pipih.' },
      { step: 2, title: 'Panggang patty', desc: 'Panggang di pan panas 3-4 menit tiap sisi hingga matang.' },
      { step: 3, title: 'Tambahkan keju', desc: 'Letakkan keju di atas patty, biarkan meleleh.' },
      { step: 4, title: 'Susun burger', desc: 'Susun roti, patty, selada, tomat, dan saus sesuai selera.' },
    ],
    tips: 'Jangan terlalu sering membalik patty agar tetap juicy.',
  },
  {
    title: 'Dimsum Ayam Udang',
    description: 'Dimsum kukus lembut dengan isian ayam dan udang segar, cocok untuk sarapan atau camilan.',
    category: 'Chinese',
    difficulty: 'Sedang',
    time: 60, price: 55000, servings: 4, rating: 4.8, reviews: 167,
    img: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '200 gr', item: 'Daging ayam cincang' },
      { amount: '150 gr', item: 'Udang, kupas dan cincang' },
      { amount: '1 sdm', item: 'Saus tiram' },
      { amount: '1 sdt', item: 'Minyak wijen' },
      { amount: '1 sdt', item: 'Kecap asin' },
      { amount: '20 lembar', item: 'Kulit dimsum' },
      { amount: 'Secukupnya', item: 'Garam dan lada putih' },
    ],
    spices: [],
    steps: [
      { step: 1, title: 'Buat isian', desc: 'Campur ayam cincang, udang, saus tiram, minyak wijen, kecap asin, garam, dan lada. Aduk rata.' },
      { step: 2, title: 'Isi kulit', desc: 'Letakkan 1 sdm isian di tengah kulit dimsum. Lipat dan bentuk sesuai selera.' },
      { step: 3, title: 'Kukus', desc: 'Kukus dimsum di atas air mendidih selama 15-20 menit hingga matang.' },
      { step: 4, title: 'Sajikan', desc: 'Sajikan dengan saus cabai atau saus kacang.' },
    ],
    tips: 'Basahi tangan saat membentuk dimsum agar tidak lengket.',
  },
  {
    title: 'Bakmi Goreng Chinese Style',
    description: 'Bakmi goreng dengan bumbu khas Chinese, gurih, dan penuh topping lezat.',
    category: 'Chinese',
    difficulty: 'Mudah',
    time: 20, price: 30000, servings: 2, rating: 4.7, reviews: 298,
    img: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '200 gr', item: 'Mie telur, rebus al dente' },
      { amount: '100 gr', item: 'Ayam fillet, iris tipis' },
      { amount: '2 butir', item: 'Telur ayam' },
      { amount: '100 gr', item: 'Sawi hijau, potong' },
      { amount: '3 siung', item: 'Bawang putih, cincang' },
      { amount: '2 sdm', item: 'Kecap asin' },
      { amount: '1 sdm', item: 'Saus tiram' },
      { amount: '1 sdt', item: 'Minyak wijen' },
    ],
    spices: [],
    steps: [
      { step: 1, title: 'Tumis bawang putih', desc: 'Tumis bawang putih dengan sedikit minyak hingga harum.' },
      { step: 2, title: 'Masak ayam', desc: 'Masukkan ayam, masak hingga berubah warna.' },
      { step: 3, title: 'Tambahkan telur', desc: 'Orak-arik telur bersama ayam.' },
      { step: 4, title: 'Masukkan mie', desc: 'Masukkan mie dan sawi, tambahkan kecap asin, saus tiram, dan minyak wijen. Aduk rata.' },
      { step: 5, title: 'Sajikan', desc: 'Sajikan panas dengan taburan bawang goreng.' },
    ],
    tips: 'Api besar saat memasak mie goreng menghasilkan aroma wok yang khas.',
  },
  {
    title: 'Pancake Fluffy Lembut',
    description: 'Pancake super fluffy dan lembut, cocok untuk sarapan atau ide jualan camilan.',
    category: 'Dessert',
    difficulty: 'Mudah',
    time: 20, price: 20000, servings: 2, rating: 4.7, reviews: 312,
    img: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '150 gr', item: 'Tepung terigu' },
      { amount: '1 sdt', item: 'Baking powder' },
      { amount: '2 sdm', item: 'Gula pasir' },
      { amount: '1 butir', item: 'Telur' },
      { amount: '180 ml', item: 'Susu cair' },
      { amount: '1 sdm', item: 'Butter, lelehkan' },
    ],
    spices: [],
    steps: [
      { step: 1, title: 'Campur bahan kering', desc: 'Campurkan tepung, baking powder, dan gula. Aduk rata.' },
      { step: 2, title: 'Campur bahan basah', desc: 'Kocok telur, susu, dan butter leleh.' },
      { step: 3, title: 'Gabungkan', desc: 'Tuang bahan basah ke kering, aduk perlahan — jangan overmix.' },
      { step: 4, title: 'Masak', desc: 'Panaskan pan anti lengket api kecil. Tuang adonan, masak hingga gelembung muncul lalu balik.' },
      { step: 5, title: 'Sajikan', desc: 'Sajikan dengan madu atau sirup maple.' },
    ],
    tips: 'Kunci fluffy: jangan overmix dan gunakan api kecil.',
  },
  {
    title: 'Tiramisu Classic',
    description: 'Dessert Italia klasik dengan lapisan krim mascarpone dan ladyfinger yang dicelup kopi.',
    category: 'Dessert',
    difficulty: 'Sedang',
    time: 45, price: 65000, servings: 6, rating: 4.9, reviews: 201,
    img: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '250 gr', item: 'Mascarpone cheese' },
      { amount: '200 ml', item: 'Krim kental (whipping cream)' },
      { amount: '3 butir', item: 'Kuning telur' },
      { amount: '4 sdm', item: 'Gula pasir' },
      { amount: '20 buah', item: 'Ladyfinger / savoiardi' },
      { amount: '200 ml', item: 'Kopi espresso, dinginkan' },
      { amount: 'Secukupnya', item: 'Bubuk coklat untuk taburan' },
    ],
    spices: [],
    steps: [
      { step: 1, title: 'Kocok krim', desc: 'Kocok whipping cream hingga soft peak. Sisihkan.' },
      { step: 2, title: 'Buat krim mascarpone', desc: 'Kocok kuning telur dan gula hingga pucat. Campurkan mascarpone, aduk rata.' },
      { step: 3, title: 'Gabungkan', desc: 'Lipat krim kocok ke dalam campuran mascarpone perlahan.' },
      { step: 4, title: 'Susun lapisan', desc: 'Celup ladyfinger ke kopi, susun di wadah. Tutup dengan krim mascarpone. Ulangi.' },
      { step: 5, title: 'Dinginkan', desc: 'Simpan di kulkas minimal 4 jam. Taburi bubuk coklat sebelum disajikan.' },
    ],
    tips: 'Tiramisu lebih enak jika didiamkan semalaman di kulkas.',
  },
  {
    title: 'Es Teh Lemon Segar',
    description: 'Minuman segar es teh lemon yang cocok untuk cuaca panas, mudah dibuat dan menyegarkan.',
    category: 'Minuman',
    difficulty: 'Mudah',
    time: 10, price: 8000, servings: 2, rating: 4.6, reviews: 98,
    img: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '2 kantong', item: 'Teh celup' },
      { amount: '500 ml', item: 'Air panas' },
      { amount: '2 buah', item: 'Lemon, peras' },
      { amount: '3 sdm', item: 'Gula pasir atau madu' },
      { amount: 'Secukupnya', item: 'Es batu' },
    ],
    spices: [],
    steps: [
      { step: 1, title: 'Seduh teh', desc: 'Seduh teh celup dalam air panas 3-5 menit. Angkat kantong teh.' },
      { step: 2, title: 'Larutkan gula', desc: 'Larutkan gula dalam teh panas. Aduk hingga larut.' },
      { step: 3, title: 'Dinginkan', desc: 'Dinginkan teh hingga suhu ruangan.' },
      { step: 4, title: 'Sajikan', desc: 'Tuang ke gelas berisi es batu, peras lemon, aduk dan sajikan.' },
    ],
    tips: 'Gunakan lemon segar untuk rasa terbaik. Bisa tambahkan daun mint.',
  },
  {
    title: 'Boba Milk Tea',
    description: 'Minuman boba milk tea kekinian yang bisa dibuat sendiri di rumah dengan mudah.',
    category: 'Minuman',
    difficulty: 'Mudah',
    time: 30, price: 15000, servings: 2, rating: 4.8, reviews: 387,
    img: 'https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1558857563-b371033873b8?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '100 gr', item: 'Mutiara tapioka (boba)' },
      { amount: '2 kantong', item: 'Teh hitam' },
      { amount: '400 ml', item: 'Susu cair' },
      { amount: '3 sdm', item: 'Gula merah, serut' },
      { amount: '2 sdm', item: 'Gula pasir' },
      { amount: 'Secukupnya', item: 'Es batu' },
    ],
    spices: [],
    steps: [
      { step: 1, title: 'Masak boba', desc: 'Rebus boba dalam air mendidih 15-20 menit hingga kenyal. Tiriskan.' },
      { step: 2, title: 'Buat sirup gula merah', desc: 'Masak gula merah dengan sedikit air hingga menjadi sirup kental.' },
      { step: 3, title: 'Seduh teh', desc: 'Seduh teh hitam dengan air panas, tambahkan gula pasir. Dinginkan.' },
      { step: 4, title: 'Susun', desc: 'Masukkan boba ke gelas, tuang sirup gula merah, es batu, teh, dan susu.' },
    ],
    tips: 'Boba paling enak dimakan dalam 2 jam setelah dimasak.',
  },
  {
    title: 'Smoothie Mangga Pisang',
    description: 'Smoothie segar dan bergizi dari mangga dan pisang, cocok untuk sarapan sehat.',
    category: 'Minuman',
    difficulty: 'Mudah',
    time: 10, price: 18000, servings: 2, rating: 4.7, reviews: 156,
    img: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=600&q=80',
    heroImg: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=1200&q=80',
    ingredients: [
      { amount: '1 buah', item: 'Mangga harum manis, kupas' },
      { amount: '2 buah', item: 'Pisang matang' },
      { amount: '200 ml', item: 'Yogurt plain' },
      { amount: '100 ml', item: 'Susu cair' },
      { amount: '1 sdm', item: 'Madu' },
      { amount: 'Secukupnya', item: 'Es batu' },
    ],
    spices: [],
    steps: [
      { step: 1, title: 'Potong buah', desc: 'Potong mangga dan pisang menjadi potongan kecil.' },
      { step: 2, title: 'Blend', desc: 'Masukkan semua bahan ke blender, blend hingga halus dan creamy.' },
      { step: 3, title: 'Sajikan', desc: 'Tuang ke gelas, tambahkan es batu. Bisa tambahkan topping granola.' },
    ],
    tips: 'Bekukan pisang semalaman untuk hasil smoothie yang lebih kental dan segar.',
  },
]

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI)
    console.log('✅ Connected to MongoDB')

    await Recipe.deleteMany({})
    console.log('🗑️  Data lama dihapus')

    await Recipe.insertMany(recipes)
    console.log(`🌱 ${recipes.length} resep berhasil ditambahkan!`)

    process.exit(0)
  } catch (error) {
    console.error('Error:', error)
    process.exit(1)
  }
}

seedDB()